# Generated by Django 5.1.15 on 2026-07-21 15:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Short intro shown under the page title."
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 4),
                            ("quote", 5),
                            ("stat_row", 11),
                            ("feature_grid", 17),
                            ("cta", 21),
                            ("embed", 22),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Large"),
                                        ("h3", "Medium"),
                                        ("h4", "Small"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("size", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "icon": "pilcrow",
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image"},
                            ),
                            5: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"icon": "openquote"},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small kicker above the number",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. '2,000+' or '4.9★'",
                                    "required": True,
                                },
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 6), ("value", 7), ("caption", 8)]],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                            11: ("wagtail.blocks.StructBlock", [[("stats", 10)]], {}),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "An emoji, e.g. 🧩", "required": False},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_emoji", 12),
                                        ("title", 0),
                                        ("body", 13),
                                        ("image", 14),
                                    ]
                                ],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("cards", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Get in touch", "required": True},
                            ),
                            19: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            20: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 0),
                                        ("text", 13),
                                        ("button_label", 18),
                                        ("button_url", 19),
                                        ("button_page", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Raw HTML for embeds/animations. Admins only.",
                                    "icon": "code",
                                    "required": False,
                                },
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_kicker",
                    models.CharField(
                        blank=True,
                        help_text="Small line above the hero heading.",
                        max_length=120,
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        blank=True, help_text="Big bold headline.", max_length=255
                    ),
                ),
                (
                    "hero_subheading",
                    models.TextField(
                        blank=True,
                        help_text="Supporting sentence under the hero heading.",
                    ),
                ),
                ("hero_cta_label", models.CharField(blank=True, max_length=60)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 4),
                            ("quote", 5),
                            ("stat_row", 11),
                            ("feature_grid", 17),
                            ("cta", 21),
                            ("embed", 22),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Large"),
                                        ("h3", "Medium"),
                                        ("h4", "Small"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("size", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "icon": "pilcrow",
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"icon": "image"},
                            ),
                            5: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"icon": "openquote"},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small kicker above the number",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. '2,000+' or '4.9★'",
                                    "required": True,
                                },
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 6), ("value", 7), ("caption", 8)]],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                            11: ("wagtail.blocks.StructBlock", [[("stats", 10)]], {}),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "An emoji, e.g. 🧩", "required": False},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_emoji", 12),
                                        ("title", 0),
                                        ("body", 13),
                                        ("image", 14),
                                    ]
                                ],
                                {},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("cards", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Get in touch", "required": True},
                            ),
                            19: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            20: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 0),
                                        ("text", 13),
                                        ("button_label", 18),
                                        ("button_url", 19),
                                        ("button_page", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Raw HTML for embeds/animations. Admins only.",
                                    "icon": "code",
                                    "required": False,
                                },
                            ),
                        },
                        help_text="Build the rest of the page from content blocks.",
                    ),
                ),
                (
                    "hero_cta_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the hero button links to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
