# Generated by Django 5.2.16 on 2026-07-21 20:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("paragraph", 3),
                    ("image", 4),
                    ("quote", 5),
                    ("stat_row", 11),
                    ("feature_grid", 17),
                    ("cta", 21),
                    ("embed", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Large"),
                                ("h3", "Medium"),
                                ("h4", "Small"),
                            ]
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("text", 0), ("size", 1)]], {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "hr"],
                            "icon": "pilcrow",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                    5: ("wagtail.blocks.BlockQuoteBlock", (), {"icon": "openquote"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small kicker above the number",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. '2,000+' or '4.9★'", "required": True},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 6), ("value", 7), ("caption", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("stats", 10)]], {}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "An emoji, e.g. 🧩", "required": False},
                    ),
                    13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_emoji", 12),
                                ("title", 0),
                                ("body", 13),
                                ("image", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 8), ("cards", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get in touch", "required": True},
                    ),
                    19: (
                        "cms.blocks.LinkURLBlock",
                        (),
                        {
                            "help_text": "A URL (https://…), a mailto:/tel: link, or a path.",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("text", 13),
                                ("button_label", 18),
                                ("button_url", 19),
                                ("button_page", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Raw HTML for embeds/animations. Admins only.",
                            "icon": "code",
                            "required": False,
                        },
                    ),
                },
                help_text="Build the rest of the page from content blocks.",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("paragraph", 3),
                    ("image", 4),
                    ("quote", 5),
                    ("stat_row", 11),
                    ("feature_grid", 17),
                    ("cta", 21),
                    ("embed", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Large"),
                                ("h3", "Medium"),
                                ("h4", "Small"),
                            ]
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("text", 0), ("size", 1)]], {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "hr"],
                            "icon": "pilcrow",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                    5: ("wagtail.blocks.BlockQuoteBlock", (), {"icon": "openquote"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small kicker above the number",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. '2,000+' or '4.9★'", "required": True},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 6), ("value", 7), ("caption", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("stats", 10)]], {}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "An emoji, e.g. 🧩", "required": False},
                    ),
                    13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    14: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_emoji", 12),
                                ("title", 0),
                                ("body", 13),
                                ("image", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 8), ("cards", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get in touch", "required": True},
                    ),
                    19: (
                        "cms.blocks.LinkURLBlock",
                        (),
                        {
                            "help_text": "A URL (https://…), a mailto:/tel: link, or a path.",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("text", 13),
                                ("button_label", 18),
                                ("button_url", 19),
                                ("button_page", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Raw HTML for embeds/animations. Admins only.",
                            "icon": "code",
                            "required": False,
                        },
                    ),
                },
            ),
        ),
    ]
