# Generated by Django 5.1.15 on 2026-07-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_rename_booking_event_puzzle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventresource",
            options={"verbose_name": "Used resource"},
        ),
        migrations.AlterModelOptions(
            name="puzzle",
            options={"ordering": ["name"], "verbose_name": "Puzzle"},
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="bookings_ev_start_71da89_idx",
            old_name="bookings_bo_start_352e72_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="bookings_ev_status_f0ebe7_idx",
            old_name="bookings_bo_status_233e96_idx",
        ),
        migrations.AlterField(
            model_name="event",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="bookings.customer",
            ),
        ),
        migrations.AlterField(
            model_name="eventresource",
            name="puzzle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_links",
                to="bookings.puzzle",
            ),
        ),
        migrations.AlterField(
            model_name="eventresource",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_links",
                to="bookings.venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventresource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("puzzle__isnull", True), ("venue__isnull", False)),
                    models.Q(("puzzle__isnull", False), ("venue__isnull", True)),
                    _connector="OR",
                ),
                name="eventresource_exactly_one_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventresource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("venue__isnull", False)),
                fields=("event", "venue"),
                name="uniq_event_venue",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventresource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("puzzle__isnull", False)),
                fields=("event", "puzzle"),
                name="uniq_event_puzzle",
            ),
        ),
    ]
