# Generated by Django 5.2.16 on 2026-07-21 20:06

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_event_venue_puzzle_reshape"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventpuzzle",
            options={
                "verbose_name": "Puzzle used",
                "verbose_name_plural": "Puzzles used",
            },
        ),
        migrations.RemoveConstraint(
            model_name="eventpuzzle",
            name="uniq_event_puzzle",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="eventpuzzle",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_puzzles",
                to="bookings.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventpuzzle",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_links",
                to="bookings.puzzle",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="answer_restrictions",
            field=models.BooleanField(
                default=False,
                help_text="Tick if the puzzle requires one exact answer. Leave unticked if it accepts a flexible range of answers.",
                verbose_name="Answer restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="hardware_required",
            field=models.TextField(
                blank=True,
                help_text="One item per line.",
                verbose_name="Hardware required",
            ),
        ),
        migrations.AlterField(
            model_name="puzzlefile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpuzzle",
            constraint=models.UniqueConstraint(
                fields=("event", "puzzle"), name="uniq_event_puzzle"
            ),
        ),
    ]
