# Generated by Django 5.2.16 on 2026-07-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_eventpuzzle_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="has_physical_components",
        ),
    ]
